version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.0.0
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  build-deploy-prod:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: '18.17'
      - node/install-packages:
          override-ci-command: npm install
      # - run:
      #     command: npm run build
      #     name: Build app
       - run:
          command: npm run generate
          name: Generate static site
      - aws-s3/copy:
          arguments: '--recursive'
          from: dist/
          to: "s3://em-opex-website"
      - run: echo "Successfully deployed to production cloudfront"
    # steps:
    #   - checkout
    #   - node/install:
    #       node-version: '16.14'
    #   - restore_cache:
    #       keys:
    #         - npm-packages-{{ checksum "package-lock.json" }}
    #   - node/install-packages:
    #       override-ci-command: npm ci
    #   - save_cache:
    #       paths:
    #         - ~/.npm
    #       key: npm-packages-{{ checksum "package-lock.json" }}
    #   - run:
    #       command: npm run generate
    #       name: Generate static site
    #   - aws-s3/sync:
    #       from: dist
    #       to: 's3://em-opex-website'
    #       arguments: |
    #         --delete \
    #         --cache-control "max-age=86400"
      # - aws-cli/setup
      # - run:
      #     name: Invalidate CloudFront
      #     command: |
      #       aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
      # - run: echo "Successfully deployed to production and invalidated CloudFront cache"
workflows:
  version: 2
  build-publish-and-deploy:
    jobs:
      - build-deploy-prod:
          filters:
            branches:
              only:
                - main