version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.0.0
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  build-deploy-prod:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Clear npm cache
          command: npm cache clean --force
      - run:
          name: Remove node_modules and package-lock.json
          command: |
            rm -rf node_modules
            rm -f package-lock.json
      - node/install-packages:
          override-ci-command: npm install
      - run:
          name: List installed packages
          command: npm list --depth=0
      - run:
          name: Debug Pinia installation
          command: |
            ls -l node_modules/pinia || echo "Pinia directory not found"
            ls -l node_modules/@pinia || echo "@pinia directory not found"
      - run:
          name: Check Pinia version
          command: npm list pinia || echo "Pinia not installed"
      - run:
          command: npm run build
          name: Build app
      - aws-s3/copy:
          arguments: '--recursive'
          from: .output/public
          to: "s3://em-opex-website"
      - run: echo "Successfully deployed to production cloudfront"
workflows:
  version: 2
  build-publish-and-deploy:
    jobs:
      - build-deploy-prod:
          filters:
            branches:
              only:
                - main